In [24]:
import numpy as np
import pandas as pd

main_path = "/Users/darkesthj/Library/CloudStorage/OneDrive-Personal/Documentos/Main.xlsx"

df = pd.read_excel(main_path, sheet_name="DataRaw")

In [25]:
df.head()

,Id,Date,Income,Investment,Return,Productivity,Studies,Clothes,10,Fixed,Food,Others,Cashout,Cash
0,1,Resto 2022,133.57,0.0,0.0,0.00,0.0,0.00,0,0.0,0.00,0.00,0.0,133.57
1,2,Octubre 2022,1960.00,0.0,0.0,1510.00,0.0,0.00,0,45.0,0.00,527.80,0.0,10.77
2,3,CTS Noviembre 2022,949.10,0.0,0.0,54.89,400.0,0.00,0,18.9,285.30,531.09,0.0,-330.31
3,4,Noviembre 2022,2120.89,0.0,0.0,668.00,400.0,169.90,0,42.9,101.45,433.45,90.0,-115.12
4,5,Grati Diciembre 2022,2596.03,0.0,0.0,299.00,0.0,98.04,0,0.0,50.60,1630.15,0.0,403.12